
import java.awt.Image;
import java.util.Scanner;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Perfil.java
 *
 * Created on 11-22-2011, 07:17:20 PM
 */
/**
 *
 * @author Gary
 */
public class Perfil extends javax.swing.JFrame {

    /** Creates new form Perfil */
    public Perfil() {
     
    
        initComponents();
    
    this.info.setText("Fecha de Nacimiento\n"+
                       "Numero de Telefono\n"+
                        "Sexo\n"+
                        "Email\n");
    
    }
    
    private ImageIcon getFoto() {
JFileChooser chooser = new JFileChooser();
chooser.setDialogTitle("Foto de Perfil");
chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
int opcion = chooser.showOpenDialog(this);
if (opcion == JFileChooser.APPROVE_OPTION){

String fotoPath = chooser.getSelectedFile().getAbsolutePath();
ImageIcon foto= new ImageIcon(fotoPath);

ImageIcon fotoReal1= new ImageIcon(foto.getImage().getScaledInstance(this.CuadroFoto.getWidth(), this.CuadroFoto.getHeight(), Image.SCALE_DEFAULT));

return fotoReal1;
}
return null;
}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        LogOut = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        info = new javax.swing.JTextPane();
        CuadroFoto = new javax.swing.JLabel();
        BotFoto = new javax.swing.JButton();
        ClickPost = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(935, 700));
        setResizable(false);
        getContentPane().setLayout(null);

        jButton1.setText("Solicitudes");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(770, 490, 140, 20);

        jButton2.setText("Buscar Amigos");
        getContentPane().add(jButton2);
        jButton2.setBounds(770, 550, 150, 30);

        jButton3.setText("Modificar Perfil");
        getContentPane().add(jButton3);
        jButton3.setBounds(770, 610, 150, 30);

        LogOut.setText("LogOut");
        LogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                LogOutMouseReleased(evt);
            }
        });
        getContentPane().add(LogOut);
        LogOut.setBounds(830, 10, 86, 23);

        jLabel2.setFont(new java.awt.Font("Microsoft Tai Le", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 255, 153));
        jLabel2.setText("FACEBINS 3.0");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 640, 229, 30);

        jLabel3.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18));
        jLabel3.setForeground(new java.awt.Color(51, 255, 102));
        jLabel3.setText("Mi Perfil");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(300, 10, 130, 30);

        info.setBackground(new java.awt.Color(102, 102, 102));
        info.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(51, 255, 102)));
        info.setForeground(new java.awt.Color(51, 255, 102));
        jScrollPane1.setViewportView(info);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 340, 150, 180);

        CuadroFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/silueta.jpg"))); // NOI18N
        CuadroFoto.setText("jLabel4");
        CuadroFoto.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(51, 255, 153)));
        getContentPane().add(CuadroFoto);
        CuadroFoto.setBounds(30, 60, 160, 170);

        BotFoto.setText("Cambiar Foto");
        BotFoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BotFotoMouseReleased(evt);
            }
        });
        getContentPane().add(BotFoto);
        BotFoto.setBounds(60, 260, 110, 23);

        ClickPost.setText("Post");
        getContentPane().add(ClickPost);
        ClickPost.setBounds(630, 160, 70, 23);

        jTextPane2.setBackground(new java.awt.Color(153, 153, 153));
        jTextPane2.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(51, 255, 102)));
        jTextPane2.setForeground(new java.awt.Color(51, 255, 153));
        jScrollPane3.setViewportView(jTextPane2);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(300, 260, 410, 370);

        jScrollPane4.setHorizontalScrollBar(null);

        jEditorPane1.setBackground(new java.awt.Color(153, 153, 153));
        jEditorPane1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 255, 102)));
        jEditorPane1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jEditorPane1KeyTyped(evt);
            }
        });
        jScrollPane4.setViewportView(jEditorPane1);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(290, 60, 420, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/social-network-1.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 930, 690);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogOutMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOutMouseReleased

        
        login lg = new login();
        
        this.dispose();
        lg.setVisible(true);

        
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_LogOutMouseReleased

    private void BotFotoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotFotoMouseReleased
ImageIcon foto= this.getFoto();

if ( foto!= null){
this.CuadroFoto.setIcon(foto);

} else {
JOptionPane.showMessageDialog(this, "Ocurrio un error");
}        // TODO add your handling code here:
    }//GEN-LAST:event_BotFotoMouseReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jEditorPane1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jEditorPane1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jEditorPane1KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Perfil().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotFoto;
    private javax.swing.JButton ClickPost;
    private javax.swing.JLabel CuadroFoto;
    private javax.swing.JButton LogOut;
    private javax.swing.JTextPane info;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextPane jTextPane2;
    // End of variables declaration//GEN-END:variables



}
